// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: tempconv.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CelsiusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Celsius       float64                `protobuf:"fixed64,1,opt,name=celsius,proto3" json:"celsius,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CelsiusRequest) Reset() {
	*x = CelsiusRequest{}
	mi := &file_tempconv_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CelsiusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CelsiusRequest) ProtoMessage() {}

func (x *CelsiusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tempconv_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CelsiusRequest.ProtoReflect.Descriptor instead.
func (*CelsiusRequest) Descriptor() ([]byte, []int) {
	return file_tempconv_proto_rawDescGZIP(), []int{0}
}

func (x *CelsiusRequest) GetCelsius() float64 {
	if x != nil {
		return x.Celsius
	}
	return 0
}

type FahrenheitReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fahrenheit    float64                `protobuf:"fixed64,1,opt,name=fahrenheit,proto3" json:"fahrenheit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FahrenheitReply) Reset() {
	*x = FahrenheitReply{}
	mi := &file_tempconv_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FahrenheitReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FahrenheitReply) ProtoMessage() {}

func (x *FahrenheitReply) ProtoReflect() protoreflect.Message {
	mi := &file_tempconv_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FahrenheitReply.ProtoReflect.Descriptor instead.
func (*FahrenheitReply) Descriptor() ([]byte, []int) {
	return file_tempconv_proto_rawDescGZIP(), []int{1}
}

func (x *FahrenheitReply) GetFahrenheit() float64 {
	if x != nil {
		return x.Fahrenheit
	}
	return 0
}

type FahrenheitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fahrenheit    float64                `protobuf:"fixed64,1,opt,name=fahrenheit,proto3" json:"fahrenheit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FahrenheitRequest) Reset() {
	*x = FahrenheitRequest{}
	mi := &file_tempconv_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FahrenheitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FahrenheitRequest) ProtoMessage() {}

func (x *FahrenheitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tempconv_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FahrenheitRequest.ProtoReflect.Descriptor instead.
func (*FahrenheitRequest) Descriptor() ([]byte, []int) {
	return file_tempconv_proto_rawDescGZIP(), []int{2}
}

func (x *FahrenheitRequest) GetFahrenheit() float64 {
	if x != nil {
		return x.Fahrenheit
	}
	return 0
}

type CelsiusReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Celsius       float64                `protobuf:"fixed64,1,opt,name=celsius,proto3" json:"celsius,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CelsiusReply) Reset() {
	*x = CelsiusReply{}
	mi := &file_tempconv_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CelsiusReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CelsiusReply) ProtoMessage() {}

func (x *CelsiusReply) ProtoReflect() protoreflect.Message {
	mi := &file_tempconv_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CelsiusReply.ProtoReflect.Descriptor instead.
func (*CelsiusReply) Descriptor() ([]byte, []int) {
	return file_tempconv_proto_rawDescGZIP(), []int{3}
}

func (x *CelsiusReply) GetCelsius() float64 {
	if x != nil {
		return x.Celsius
	}
	return 0
}

var File_tempconv_proto protoreflect.FileDescriptor

const file_tempconv_proto_rawDesc = "" +
	"\n" +
	"\x0etempconv.proto\x12\btempconv\"*\n" +
	"\x0eCelsiusRequest\x12\x18\n" +
	"\acelsius\x18\x01 \x01(\x01R\acelsius\"1\n" +
	"\x0fFahrenheitReply\x12\x1e\n" +
	"\n" +
	"fahrenheit\x18\x01 \x01(\x01R\n" +
	"fahrenheit\"3\n" +
	"\x11FahrenheitRequest\x12\x1e\n" +
	"\n" +
	"fahrenheit\x18\x01 \x01(\x01R\n" +
	"fahrenheit\"(\n" +
	"\fCelsiusReply\x12\x18\n" +
	"\acelsius\x18\x01 \x01(\x01R\acelsius2\xa9\x01\n" +
	"\x0fTempConvService\x12J\n" +
	"\x13CelsiusToFahrenheit\x12\x18.tempconv.CelsiusRequest\x1a\x19.tempconv.FahrenheitReply\x12J\n" +
	"\x13FahrenheitToCelsius\x12\x1b.tempconv.FahrenheitRequest\x1a\x16.tempconv.CelsiusReplyB3Z1github.com/Nandana12019/tempconv-grpc/proto;protob\x06proto3"

var (
	file_tempconv_proto_rawDescOnce sync.Once
	file_tempconv_proto_rawDescData []byte
)

func file_tempconv_proto_rawDescGZIP() []byte {
	file_tempconv_proto_rawDescOnce.Do(func() {
		file_tempconv_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tempconv_proto_rawDesc), len(file_tempconv_proto_rawDesc)))
	})
	return file_tempconv_proto_rawDescData
}

var file_tempconv_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_tempconv_proto_goTypes = []any{
	(*CelsiusRequest)(nil),    // 0: tempconv.CelsiusRequest
	(*FahrenheitReply)(nil),   // 1: tempconv.FahrenheitReply
	(*FahrenheitRequest)(nil), // 2: tempconv.FahrenheitRequest
	(*CelsiusReply)(nil),      // 3: tempconv.CelsiusReply
}
var file_tempconv_proto_depIdxs = []int32{
	0, // 0: tempconv.TempConvService.CelsiusToFahrenheit:input_type -> tempconv.CelsiusRequest
	2, // 1: tempconv.TempConvService.FahrenheitToCelsius:input_type -> tempconv.FahrenheitRequest
	1, // 2: tempconv.TempConvService.CelsiusToFahrenheit:output_type -> tempconv.FahrenheitReply
	3, // 3: tempconv.TempConvService.FahrenheitToCelsius:output_type -> tempconv.CelsiusReply
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_tempconv_proto_init() }
func file_tempconv_proto_init() {
	if File_tempconv_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tempconv_proto_rawDesc), len(file_tempconv_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_tempconv_proto_goTypes,
		DependencyIndexes: file_tempconv_proto_depIdxs,
		MessageInfos:      file_tempconv_proto_msgTypes,
	}.Build()
	File_tempconv_proto = out.File
	file_tempconv_proto_goTypes = nil
	file_tempconv_proto_depIdxs = nil
}
